spring.datasource:
  hikari.maximum-pool-size: 4
  url: ${DB_URL}
  username: ${DB_USERNAME}
  password: ${DB_PW}
  platform: postgres

jwt:
  secret-key: sol_fc_sns.sns-application-2022.secret_key
  # 30d days
  token.expired-time-ms: 2592000000

spring.redis.url: ${REDIS_URL}

spring:
  kafka:
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: SCRAM-SHA-256
      sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PW}";
    consumer:
      properties.spring.json.trusted.packages: "*"
      bootstrap-servers: moped.srvs.cloudkafka.com:9094
      group-id: kqdravip-notification
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    listener:
      ack-mode: MANUAL
    producer:
      bootstrap-servers: moped.srvs.cloudkafka.com:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties.enable.idempotence: false
    topic:
      notification: kqdravip-notification