spring.datasource:
  hikari.maximum-pool-size: 10
  url: ${DB_URL}
  username: ${DB_USERNAME}
  password: ${DB_PW}
  platform: postgres

logging.level.org.springframework.jdbc.core.JdbcTemplate: DEBUG

jwt:
  secret-key: sol_fc_sns.sns-application-2022.secret_key
  # 30d days
  token.expired-time-ms: 2592000000

spring.redis.url: ${REDIS_URL}

spring:
  kafka:
    consumer:
      properties.spring.json.trusted.packages: "*"
      bootstrap-servers: localhost:9092
      group-id: sns-alarm
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    listener:
      ack-mode: MANUAL # 수동으로 ack를 날림
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    topic:
      alarm: alarm